### ISSUE TITLE
white spaces in string are deleted

### ISSUE THREAD

**Issue by PaulXiCao** [jannisteunissen/config_fortran#10]
Spaces within a string variable are deleted.

Example config file:
```
str = foo bar
```
Expected value in variable
```fortan
character(:), allocatable :: 
var = "foo bar"
```
actual value in variable
```fortan
var = "foobar"
```

**Comment by jannisteunissen** [comment]
Thanks for reporting this, that is indeed a bit strange! I've fixed this behavior in the latest version, what you should now get in your example depends on how you define 'str':

``call CFG_add(cfg, "str", [""], "comment", dynamic_size=.true.)``
and then reading the input will give 'foo' 'bar' (since 'str' is a variable-size array of strings)

``call CFG_add(cfg, "str", "", "comment", dynamic_size=.true.)``
and then reading the input will give 'foo bar' (since 'str' is a scalar string)

**Comment by jannisteunissen** [comment]
I'll close this issue, please let me know if you have further comments.
